name: Rust

on:
  push:
  pull_request:

env:
  RUSTFLAGS: '-Dwarnings'
  CARGO_TERM_COLOR: always

jobs:
  check:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2
      - name: rust-toolchain
        uses: dtolnay/rust-toolchain@1.70.0
        with:
          toolchain: nightly-2022-12-06
          components: clippy, rustfmt
      - uses: Swatinem/rust-cache@v2
      - name: Check
        run: cargo clippy --all-targets --all-features --tests --benches
      - name: Run tests
        run: cargo test --verbose

  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2
      - name: rust-toolchain
        uses: dtolnay/rust-toolchain@1.70.0
        with:
          toolchain: nightly-2022-12-06
      - uses: Swatinem/rust-cache@v2
      - name: Build
        run: cargo build --verbose --release

  test:
    name: Tests
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: rust-toolchain
        uses: dtolnay/rust-toolchain@1.70.0
        with:
          toolchain: nightly-2022-12-06
      - uses: Swatinem/rust-cache@v2
      - uses: taiki-e/install-action@v1
        with:
          tool: cargo-nextest
      - name: Test
        run: cargo nextest run

  fmt:
    name: Rustfmt
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: rust-toolchain
        uses: dtolnay/rust-toolchain@1.70.0
        with:
          toolchain: nightly-2022-12-06
          components: rustfmt
      - uses: Swatinem/rust-cache@v2
      - uses: actions-rs/cargo@v1
        with:
          command: fmt
          args: --all -- --check
