name: Rust

on:
  push:
  pull_request:

env:
  RUSTFLAGS: '-Dwarnings'
  CARGO_TERM_COLOR: always

jobs:
  checks:
    name: Checks
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2
        name: Git checkout
      - name: Toolchain
        run: rustup show
      - uses: Swatinem/rust-cache@v2
        name: Cache
      - name: Clippy
        run: cargo clippy --all-targets --all-features --tests --benches
      - uses: actions-rs/cargo@v1
        name: Fmt
        with:
          command: fmt
          args: --all -- --check

  build:
    name: Build
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2
        name: Git checkout
      - name: Toolchain
        run: rustup show
      - uses: Swatinem/rust-cache@v2
        name: Cache
      - name: Build
        run: cargo build --verbose --release

  test:
    name: Tests
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
        name: Git checkout
      - name: Toolchain
        run: rustup show
      - uses: Swatinem/rust-cache@v2
        name: Cache
      - uses: taiki-e/install-action@v1
        with:
          tool: cargo-nextest
      - name: Test
        run: cargo nextest run
